const data = {
    products: [
        {
            _id: '1',
            name: 'Raymond Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 999,
            brand: 'Raymond',
            rating: 4.5,
            numReviews: 19,
            description: 'Men Slim Fit Solid Formal Shirt',
        },
        {
            _id: '2',
            name: 'Men Black Jeans',
            category: 'Jeans',
            image: '/images/p2.jpg',
            price: 1649,
            brand: 'Pepe Jeans',
            rating: 4.2,
            numReviews: 13,
            description: 'Tapered Fit Men Black Jeans',
        },
        {
            _id: '3',
            name: 'Polyester Viscose Blend Trousers',
            category: 'Trousers',
            image: '/images/p3.jpg',
            price: 999,
            brand: 'Peter England',
            rating: 4.1,
            numReviews: 16,
            description: 'Slim Fit Men Grey Polyester Viscose Blend Trousers',
        },
        {
            _id: '4',
            name: 'Men Waistcoat',
            category: 'Waistcoat',
            image: '/images/p4.jpg',
            price: 2499,
            brand: 'Louis Philippe',
            rating: 4.3,
            numReviews: 9,
            description: 'Self Design Men Waistcoat',
        },
        {
            _id: '5',
            name: 'Cotton Straight Kurta',
            category: 'Kurta',
            image: '/images/p5.jpg',
            price: 2144,
            brand: 'Raymond',
            rating: 4.2,
            numReviews: 13,
            description: 'Men Solid Pure Cotton Straight Kurta(Red)',
        },
        {
            _id: '6',
            name: 'Round Neck T-Shirt',
            category: 'T-Shirts',
            image: '/images/p6.jpg',
            price: 1199,
            brand: 'Puma',
            rating: 3.8,
            numReviews: 18,
            description: 'Printed Men Round Neck Blue T-Shirt',
        },
    ],
};

export default data;